# Copyright 2001-2011, Paul Johnson (pjcj@cpan.org)

# This software is free.  It is licensed under the same terms as Perl itself.

# The latest version of this software should be available from my homepage:
# http://www.pjcj.net

# This file was automatically generated by Makefile.PL.

package Devel::Cover::Inc;

use strict;
use warnings;

our $VERSION      = "0.79";
our $Perl_version = '5.014002';
our $Base         = 'C:/strawberry/cpan/build/Devel-Cover-0.79-gWrxqg';
our @Inc          = qw( . C:/DOCUME~1/GABORS~1/LOCALS~1/Temp/CPAN-Reporter-lib-72u3 C:/strawberry/perl/lib C:/strawberry/perl/site/lib C:/strawberry/perl/vendor/lib );
chomp (our $Perl  = <<'EOV');  # Careful with \\ in the path
C:\strawberry\perl\bin\perl.exe
EOV

if ($Perl_version ne $])
{
    print STDERR <<"EOM";

This version of Devel::Cover was built with Perl version $Perl_version.
It is now being run with Perl version $].
Attempting to make adjustments, but you may find that some of your modules do
not have coverage data collected.  You may need to alter the +-inc, +-ignore
and +-select options.

EOM
    eval "use Cwd";
    my %inc = map { -d $_ ? (($_ eq "." ? $_ : Cwd::abs_path($_)) => 1) : () }
                   @INC;
    @Inc = sort keys %inc;
}

# TODO - check for threadedness, 64bits etc. ?

1
